### ISSUE TITLE
Preview post feature produces garbled text

### ISSUE THREAD

**Issue by dewheel** [Flameborn/Kiramoji#3]
The following text (skillful SJIS art of a baby) comes out garbled when the preview post feature is used:
```
　　　　 　　　 　 　　　 　　　 ,　-‐　　- 、
　　　　　　　　　 　 　 　 ／　　　　　　 　 、
　　　　　　　　　　　　　,'　　　　　　　 　 　 、
　　　　　　　　　　　　　|　　　　　　　　　　　',
　　　　　　　　　　　　　|　　　　　　　　 　 　 l
　　　　　　　　　　　　 〈ヽ　　-‐-　　-‐- 　 '
　　　　, - r '´￣￣￣　ヽ　 く●〉　 〈●ｱ ,'
　　　/　　l　　　／　 　 　 、　　 r_ _ｭ　 　 !
.　　/　 　 !　　,'　　 　 　 　 、　ﾄｪｪｪｪｲ　ノ|　　babubabu
　　l　　　　、　　 /　　　　ヽ　ー`＝＝′ '∧
　　}　　　　 、 　 !　　　　　 i　　＼__ﾉ　 /　 ヽ
　　!　　　　　＼ ﾉ　　　　　 ,　/　　　／＼__ ノヽ
　 /、　　　　 　 ト、　　　　　/　　_, ' 　 　 ＼　　 、
　(　ヽ　　　　　 |　｀ー-　__ノ-‐ ´　　　　　　 ＼ - ーｧ
　 ＼_ヽ　　　　ﾉ　　 ﾞ、　　', 　 　 　 　 　 　 　 し‐､_ミ
　　　 ￣￣￣　　　 　ヽ　　ヽ
　　　　 　 　 　 　 　 　 ヽ　　ヽ
　　 　 　 　 　 　 　 　 　 ヽ _ノ ー、
　　　　　　　　　　　　　　　| , , , ｢.. 
```

When posted it comes out just fine as long as formatting is set to "Text art". [Here](https://files.catbox.moe/sapjxa.png)'s a screenshot of the issue. This issue can be reproduced on https://kiramoji.ga/

**Comment by Flameborn** [comment]
Thanks for reporting this.

It looks like the fields were encoded via *encodeURIComponent* using javascript, but the Perl backend did not decode the query parameter, and the returned response had no *charset* defined, either.

It should be fixed now.
