### ISSUE TITLE
Request for Internet Time format

### ISSUE THREAD

**Issue by chaoskaiser72** [Flameborn/Kiramoji#5]
Internet Time was a campaign by Swiss watchmaker Swatch to create a standardized time format with no time zones: in it, each day is made up of one thousand "beats" which equal 86.4 seconds. It was used in the early MMO Phantasy Star Online and the chat client ICQ, adopted by CNN's homepage for a time, and is supported natively by PHP. I've been seeing small webpages and forums around the web adopt it lately, and I think it would be really neat to have as an option in Kiramoji. There are code snippets for multiple languages to convert UTC to Internet Time, so it shouldn't be hard to add with Perl.

https://en.wikipedia.org/wiki/Swatch_Internet_Time
http://gwil.co/internet-time/
https://wiki.melonland.net/swatch_time

**Comment by Flameborn** [comment]
Looks like this is a fun feature to implement, I will look into it. Thanks for the detailed description.

**Comment by Flameborn** [comment]
This should be available now, configurable via the *swatch* date style in config.pl. A new release will follow shortly.
